name: class_todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter_riverpod: ^2.4.0
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.2
  flutter_native_splash: ^2.3.2
  go_router: ^11.0.0
  shared_preferences: ^2.2.1
  firebase_app_check: ^0.2.0
  url_launcher: ^6.1.14
  http: ^1.1.0
  google_sign_in: ^6.2.1
  grouped_list: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/icon.png
  android_12:
    image: assets/img/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/appicon.png"
    background_color: "#32a7d1"
    theme_color: "#32a7d1"