name: class_todo_list
description: "A fully shared online contact book"
publish_to: "none"
version: 2.2.0+24

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_app_check: ^0.3.1+2
  cloud_firestore: ^5.4.2
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.2
  flutter_native_splash: ^2.3.2
  go_router: ^11.0.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  http: ^1.1.0
  google_sign_in: ^6.2.1
  grouped_list: ^6.0.0
  intl: ^0.19.0
  dart_rss: ^3.0.3
  flutter_widget_from_html_core: ^0.15.2
  cupertino_icons: ^1.0.8
  share_plus: ^10.0.2
  font_awesome_flutter: ^10.7.0
  crypto: ^3.0.5
  package_info_plus: ^8.0.2
  googleapis: ^13.2.0
  rxdart: ^0.28.0
  toastification: ^2.3.0
  smooth_page_indicator: ^1.2.0+3
  firebase_remote_config: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/config/

flutter_native_splash:
  color: "#f3f2f7"
  color_dark: "#101316"
  image: assets/img/icon.png
  android_12:
    color: "#f3f2f7"
    color_dark: "#101316"
    image: assets/img/android12_splash_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/img/icon.png"
  web:
    generate: true
    image_path: "assets/img/appicon.png"
    background_color: "#32a7d1"
    theme_color: "#32a7d1"
