// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP8mfMRzHJkU37ulS2XqEW2cenbXeCB_M',
    appId: '1:65396233679:web:8aa53eb5ec9914e4536eba',
    messagingSenderId: '65396233679',
    projectId: 'class-todo-list',
    authDomain: 'class-todo-list.firebaseapp.com',
    storageBucket: 'class-todo-list.appspot.com',
    measurementId: 'G-EMG40G9987',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVNLMQvKBMl1n28Psd-HkNtoh-ny2NAlo',
    appId: '1:65396233679:ios:fa06ef83c83f87bc536eba',
    messagingSenderId: '65396233679',
    projectId: 'class-todo-list',
    storageBucket: 'class-todo-list.appspot.com',
    androidClientId: '65396233679-73rhj9jdq247svj1ptu4gjo1q44eev0j.apps.googleusercontent.com',
    iosClientId: '65396233679-31se8450oaah8viiqqtob4h9omb0durk.apps.googleusercontent.com',
    iosBundleId: 'com.ycy.classtodo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUMrV3B6DgRuvY9ptsX3niYBAvRz_Axl8',
    appId: '1:65396233679:android:427f47da3c362aaa536eba',
    messagingSenderId: '65396233679',
    projectId: 'class-todo-list',
    storageBucket: 'class-todo-list.appspot.com',
  );

}